### ISSUE TITLE
Launcher.apk launcher error

### ISSUE THREAD

**Issue by leiyuanhua** [AnderWeb/android_packages_apps_Launcher#32]
when launcher the Launcher.apk,if you print the log you will see:
I/ActivityManager(  126): Starting activity: Intent { act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10200000 cmp=com.android.launcher/.Launcher }
I/ActivityManager(  126): Start proc android.process.acore for activity com.android.launcher/.Launcher: pid=8385 uid=10000 gids={3003, 1015}
I/ActivityThread( 8385): Publishing provider com.android.social: com.android.providers.contacts.SocialProvider
I/ActivityThread( 8385): Publishing provider applications: com.android.providers.applications.ApplicationsProvider
I/ActivityThread( 8385): Publishing provider com.android.launcher.settings: com.android.launcher.LauncherProvider
I/ActivityThread( 8385): Publishing provider contacts;com.android.contacts: com.android.providers.contacts.ContactsProvider2
I/ActivityThread( 8385): Publishing provider call_log: com.android.providers.contacts.CallLogProvider
I/ActivityThread( 8385): Publishing provider user_dictionary: com.android.providers.userdictionary.UserDictionaryProvider
D/Launcher( 8385): ONCREATE

D/CELLLAYOUT( 8385): onMeasure!!! portrait=true
D/CELLLAYOUT( 8385): onMeasure!!! portrait=true
D/CELLLAYOUT( 8385): onMeasure!!! portrait=true
E/sqlite3_android( 8385): Can't open transliterator. Error: U_INVALID_ID
D/CELLLAYOUT( 8385): onMeasure!!! portrait=true
D/CELLLAYOUT( 8385): onMeasure!!! portrait=true
D/LauncherProvider( 8385): creating new launcher database
D/LauncherProvider( 8385): converting database from an older format, but not onUpgrade
D/CELLLAYOUT( 8385): onMeasure!!! portrait=true
D/CELLLAYOUT( 8385): onMeasure!!! portrait=true
W/LauncherProvider( 8385): Unable to add favorite: com.android.gallery/com.android.camera.GalleryPicker
W/LauncherProvider( 8385): android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{com.android.gallery/com.android.camera.GalleryPicker}
W/LauncherProvider( 8385):  at android.app.ContextImpl$ApplicationPackageManager.getActivityInfo(ContextImpl.java:1795)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherProvider$DatabaseHelper.addAppShortcut(LauncherProvider.java:585)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherProvider$DatabaseHelper.loadFavorites(LauncherProvider.java:546)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherProvider$DatabaseHelper.onCreate(LauncherProvider.java:251)
W/LauncherProvider( 8385):  at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:106)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherProvider.query(LauncherProvider.java:109)
W/LauncherProvider( 8385):  at android.content.ContentProvider$Transport.query(ContentProvider.java:163)
W/LauncherProvider( 8385):  at android.content.ContentResolver.query(ContentResolver.java:245)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherModel$DesktopItemsLoader.updateShortcutLabels(LauncherModel.java:983)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherModel$DesktopItemsLoader.load_workspace(LauncherModel.java:732)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherModel$DesktopItemsLoader.run(LauncherModel.java:718)
W/LauncherProvider( 8385):  at java.lang.Thread.run(Thread.java:1096)
D/CELLLAYOUT( 8385): onMeasure!!! portrait=true
D/CELLLAYOUT( 8385): onMeasure!!! portrait=true
D/CELLLAYOUT( 8385): onMeasure!!! portrait=true
W/LauncherProvider( 8385): Unable to add favorite: com.google.android.apps.maps/com.google.android.maps.MapsActivity
W/LauncherProvider( 8385): android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{com.google.android.apps.maps/com.google.android.maps.MapsActivity}
W/LauncherProvider( 8385):  at android.app.ContextImpl$ApplicationPackageManager.getActivityInfo(ContextImpl.java:1795)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherProvider$DatabaseHelper.addAppShortcut(LauncherProvider.java:585)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherProvider$DatabaseHelper.loadFavorites(LauncherProvider.java:546)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherProvider$DatabaseHelper.onCreate(LauncherProvider.java:251)
W/LauncherProvider( 8385):  at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:106)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherProvider.query(LauncherProvider.java:109)
W/LauncherProvider( 8385):  at android.content.ContentProvider$Transport.query(ContentProvider.java:163)
W/LauncherProvider( 8385):  at android.content.ContentResolver.query(ContentResolver.java:245)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherModel$DesktopItemsLoader.updateShortcutLabels(LauncherModel.java:983)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherModel$DesktopItemsLoader.load_workspace(LauncherModel.java:732)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherModel$DesktopItemsLoader.run(LauncherModel.java:718)
W/LauncherProvider( 8385):  at java.lang.Thread.run(Thread.java:1096)
W/LauncherProvider( 8385): Unable to add favorite: com.android.vending/com.android.vending.AssetBrowserActivity
W/LauncherProvider( 8385): android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{com.android.vending/com.android.vending.AssetBrowserActivity}
W/LauncherProvider( 8385):  at android.app.ContextImpl$ApplicationPackageManager.getActivityInfo(ContextImpl.java:1795)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherProvider$DatabaseHelper.addAppShortcut(LauncherProvider.java:585)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherProvider$DatabaseHelper.loadFavorites(LauncherProvider.java:546)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherProvider$DatabaseHelper.onCreate(LauncherProvider.java:251)
W/LauncherProvider( 8385):  at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:106)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherProvider.query(LauncherProvider.java:109)
W/LauncherProvider( 8385):  at android.content.ContentProvider$Transport.query(ContentProvider.java:163)
W/LauncherProvider( 8385):  at android.content.ContentResolver.query(ContentResolver.java:245)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherModel$DesktopItemsLoader.updateShortcutLabels(LauncherModel.java:983)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherModel$DesktopItemsLoader.load_workspace(LauncherModel.java:732)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherModel$DesktopItemsLoader.run(LauncherModel.java:718)
W/LauncherProvider( 8385):  at java.lang.Thread.run(Thread.java:1096)
W/LauncherProvider( 8385): Unable to add favorite: com.google.android.gm/com.google.android.gm.ConversationListActivityGmail
W/LauncherProvider( 8385): android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{com.google.android.gm/com.google.android.gm.ConversationListActivityGmail}
W/LauncherProvider( 8385):  at android.app.ContextImpl$ApplicationPackageManager.getActivityInfo(ContextImpl.java:1795)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherProvider$DatabaseHelper.addAppShortcut(LauncherProvider.java:585)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherProvider$DatabaseHelper.loadFavorites(LauncherProvider.java:546)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherProvider$DatabaseHelper.onCreate(LauncherProvider.java:251)
W/LauncherProvider( 8385):  at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:106)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherProvider.query(LauncherProvider.java:109)
W/LauncherProvider( 8385):  at android.content.ContentProvider$Transport.query(ContentProvider.java:163)
W/LauncherProvider( 8385):  at android.content.ContentResolver.query(ContentResolver.java:245)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherModel$DesktopItemsLoader.updateShortcutLabels(LauncherModel.java:983)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherModel$DesktopItemsLoader.load_workspace(LauncherModel.java:732)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherModel$DesktopItemsLoader.run(LauncherModel.java:718)
W/LauncherProvider( 8385):  at java.lang.Thread.run(Thread.java:1096)
W/LauncherProvider( 8385): Unable to add favorite: com.google.android.talk/com.google.android.talk.SigningInActivity
W/LauncherProvider( 8385): android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{com.google.android.talk/com.google.android.talk.SigningInActivity}
W/LauncherProvider( 8385):  at android.app.ContextImpl$ApplicationPackageManager.getActivityInfo(ContextImpl.java:1795)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherProvider$DatabaseHelper.addAppShortcut(LauncherProvider.java:585)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherProvider$DatabaseHelper.loadFavorites(LauncherProvider.java:546)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherProvider$DatabaseHelper.onCreate(LauncherProvider.java:251)
W/LauncherProvider( 8385):  at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:106)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherProvider.query(LauncherProvider.java:109)
W/LauncherProvider( 8385):  at android.content.ContentProvider$Transport.query(ContentProvider.java:163)
W/LauncherProvider( 8385):  at android.content.ContentResolver.query(ContentResolver.java:245)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherModel$DesktopItemsLoader.updateShortcutLabels(LauncherModel.java:983)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherModel$DesktopItemsLoader.load_workspace(LauncherModel.java:732)
W/LauncherProvider( 8385):  at com.android.launcher.LauncherModel$DesktopItemsLoader.run(LauncherModel.java:718)
W/LauncherProvider( 8385):  at java.lang.Thread.run(Thread.java:1096)
I/ActivityManager(  126): Displayed activity com.android.launcher/.Launcher: 2964 ms (total 2964 ms)
D/HomeLoaders( 8385):   ----> items cloned, ready to refresh UI
D/CELLLAYOUT( 8385): onMeasure!!! portrait=true
D/CELLLAYOUT( 8385): onMeasure!!! portrait=true
D/Launcher( 8385): about to setAppWidget for id=14, info=AppWidgetProviderInfo(provider=ComponentInfo{com.android.quicksearchbox/com.android.quicksearchbox.SearchWidgetProvider})
D/CELLLAYOUT( 8385): onMeasure!!! portrait=true
note this line:
E/sqlite3_android( 8385): Can't open transliterator. Error: U_INVALID_ID
Why is this error？

**Comment by AnderWeb** [comment]
Which error?
The "android.content.pm.PackageManager$NameNotFoundException" one?
Thats cause at the first boot it tries to create a default set of shortcuts to desktop, but if the app is not installed that's showed in logcat. But not a real error.

Also.... what version are you running? The "D/CELLLAYOUT( 8385): onMeasure!!!" line should not be appearing...

**Comment by leiyuanhua** [comment]
I use the version 1.13,why before launcher create start so many thread?
why duration start the launcher.apk appear so many warning and have a error like this line:E/sqlite3_android( 8385): Can't open transliterator. Error: U_INVALID_ID?

**Comment by leiyuanhua** [comment]
can you tell me how to prevent :create a default set of shortcuts to desktop?

**Comment by leiyuanhua** [comment]
I think the error:
E/sqlite3_android( 8385): Can't open transliterator. Error: U_INVALID_ID? 
mayby cause by  
static class ApplicationInfoComparator implements Comparator<ApplicationInfo> {
        public final int compare(ApplicationInfo a, ApplicationInfo b) {
            return sCollator.compare(a.title.toString(), b.title.toString());
        }
    }
At present I do not know how to modify the error

**Comment by AnderWeb** [comment]
1-What is "so many thread"?
2-To prevent default set of shortcuts, edit the default_workspace.xml
3-I don't know what's the "transliterator error", but seems related to the android framework translation stuff. Maybe app names written in foreign laungages with special charcodes throw any kind of error when trying to compare strings? I don't know.

**Comment by leiyuanhua** [comment]
when start the ADW Launcher from the logcat you can see:
I/ActivityThread( 8385): Publishing provider com.android.social: com.android.providers.contacts.SocialProvider
I/ActivityThread( 8385): Publishing provider applications: com.android.providers.applications.ApplicationsProvider
I/ActivityThread( 8385): Publishing provider com.android.launcher.settings: com.android.launcher.LauncherProvider
I/ActivityThread( 8385): Publishing provider contacts;com.android.contacts: com.android.providers.contacts.ContactsProvider2
I/ActivityThread( 8385): Publishing provider call_log: com.android.providers.contacts.CallLogProvider
I/ActivityThread( 8385): Publishing provider user_dictionary: com.android.providers.userdictionary.UserDictionaryProvider

but use the google's android2.2 Launcher2.apk only start one thread as follow：
I/ActivityThread( 8238): Publishing provider com.android.launcher2.settings: com.android.launcher2.LauncherProvider

use the google's android2.2 Launcher2.apk  not appear the error:
E/sqlite3_android( 8385): Can't open transliterator. Error: U_INVALID_ID

mayby this error cause by ADW Launcher

**Comment by AnderWeb** [comment]
Have you tried to test both launchers with the same widgets?

**Comment by leiyuanhua** [comment]
yes,I test many times in my phone,and the phone's widgets is the same
