### ISSUE TITLE
Screen rotation error

### ISSUE THREAD

**Issue by leiyuanhua** [AnderWeb/android_packages_apps_Launcher#46]
Rotation the phone,when the screen orientation changing,if you adb shell logcat you will see as follow:
I/WindowManager(  130): Setting rotation to 1, animFlags=0
I/ActivityManager(  130): Config changed: { scale=1.0 imsi=0/0 loc=zh_CN touch=3 keys=1/1/2 nav=3/1 orien=2 layout=18 uiMode=17 seq=11}
I/UsageStats(  130): Unexpected resume of com.android.launcher while already resumed in com.android.launcher
W/System.err(17208): java.lang.IllegalArgumentException: Receiver not registered: mobi.intuitit.android.widget.WidgetSpace$1@45266820
W/System.err(17208):    at android.app.ActivityThread$PackageInfo.forgetReceiverDispatcher(ActivityThread.java:793)
W/System.err(17208):    at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:814)
W/System.err(17208):    at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:331)
W/System.err(17208):    at mobi.intuitit.android.widget.WidgetSpace.unregisterReceiver(WidgetSpace.java:720)
W/System.err(17208):    at mobi.intuitit.android.widget.WidgetSpace.unregisterProvider(WidgetSpace.java:708)
W/System.err(17208):    at com.android.launcher.Launcher.onDestroy(Launcher.java:1282)
W/System.err(17208):    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3642)
W/System.err(17208):    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3673)
W/System.err(17208):    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3789)
W/System.err(17208):    at android.app.ActivityThread.access$2400(ActivityThread.java:125)
W/System.err(17208):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2037)
W/System.err(17208):    at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(17208):    at android.os.Looper.loop(Looper.java:123)
W/System.err(17208):    at android.app.ActivityThread.main(ActivityThread.java:4627)
W/System.err(17208):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(17208):    at java.lang.reflect.Method.invoke(Method.java:521)
W/System.err(17208):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:876)
W/System.err(17208):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
W/System.err(17208):    at dalvik.system.NativeStart.main(Native Method)
W/System.err(17208): java.lang.IllegalArgumentException: Receiver not registered: mobi.intuitit.android.widget.WidgetSpace$ScrollViewProvider@45266850
W/System.err(17208):    at android.app.ActivityThread$PackageInfo.forgetReceiverDispatcher(ActivityThread.java:793)
W/System.err(17208):    at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:814)
W/System.err(17208):    at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:331)
W/System.err(17208):    at mobi.intuitit.android.widget.WidgetSpace.unregisterReceiver(WidgetSpace.java:720)
W/System.err(17208):    at mobi.intuitit.android.widget.WidgetSpace.unregisterProvider(WidgetSpace.java:709)
W/System.err(17208):    at com.android.launcher.Launcher.onDestroy(Launcher.java:1282)
W/System.err(17208):    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3642)
W/System.err(17208):    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3673)
W/System.err(17208):    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3789)
W/System.err(17208):    at android.app.ActivityThread.access$2400(ActivityThread.java:125)
W/System.err(17208):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2037)
W/System.err(17208):    at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(17208):    at android.os.Looper.loop(Looper.java:123)
W/System.err(17208):    at android.app.ActivityThread.main(ActivityThread.java:4627)
W/System.err(17208):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(17208):    at java.lang.reflect.Method.invoke(Method.java:521)
W/System.err(17208):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:876)
W/System.err(17208):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
W/System.err(17208):    at dalvik.system.NativeStart.main(Native Method)
D/Launcher(17208): ONCREATE
W/AppWidgetHostView(17208): can't inflate defaultView because mInfo is missing
was wrong?

**Comment by leiyuanhua** [comment]
W/System.err(17208): at com.android.launcher.Launcher.onDestroy(Launcher.java:1282)
I fixed the error:
in onDestroy() modify mWorkspace.unregisterProvider(); to
if (scrollableSupport) mWorkspace.unregisterProvider();
will be OK!
